### ISSUE TITLE
Question about the dr/dxi in the pi factor

### ISSUE THREAD

**Issue by DeepRobot2020** [prime-slam/mrob#62]
Hi,

Could I ask how the below results are derived? 
```c++
  // dr/dxi = sqrt(S)'* T' * G' * pi = sqrt(S)'* T' * [normal^ | 0 0 0  ]
    //                                                   0 0 0   | normal']
```
https://github.com/prime-slam/mrob/blob/c005a51076c4b3b162320014053bc0d64abdd62c/src/plane-surfaces/factors/PiFactorPlane.cpp#L75

Based on [barfoot_ser17.pdf](http://asrl.utias.utoronto.ca/~tdb/bib/barfoot_ser17.pdf) eq(7.159), the results seem should be 
sqrt(S)'* T' * [d, d, d, -normal^ 
                        0^T, 0^T] 
where n is the plane normal and d is the distance to origin.

**Comment by DeepRobot2020** [comment]
Below is my derivation process, not sure where I did wrong. 
![Screenshot from 2024-03-21 11-22-46](https://github.com/prime-slam/mrob/assets/6764480/5dbcc297-f786-40c9-8b9f-8ab35b8d986c)

**Comment by DeepRobot2020** [comment]
I found the mistakes in my derivation, and I can confirm the math in the above code is correct. 
Thanks for the opening source this project.

**Comment by g-ferrer** [comment]
Yes, I see your point. On the convention, I am following this: xi = [theta, pho], so many things compered to Barfoot's book require re-arrangement.
Thanks for your comment!
